Fix `make images` and GHA
`make images` had been broken since d56ddccf0aeb96e56d72af28b7eb8589cf27f31f:
- The context path was not specified in `docker buildx build`
- Registry cache was always specified even for local builds
- Rootless image was not built

Also, GHA didn't build the rootless image as well.

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

diff --git a/hack/images b/hack/images
--- a/hack/images
+++ b/hack/images
@@ -25,9 +25,21 @@ if [ -z "$TAG" ] || [ -z "$REPO" ]; then
   usage
 fi
 
-pushFlag="push=false"
+localmode=""
+if [[ "$TAG" == local* ]]; then
+  localmode="1"
+  if [ "$PUSH" = "push" ]; then
+    echo >&2 "local images cannot be pushed"
+    exit 1
+  fi
+fi
+
+outputFlag="--output=type=image,push=false"
 if [ "$PUSH" = "push" ]; then
-  pushFlag="push=true"
+  outputFlag="--output=type=image,push=true"
+fi
+if [ -n "$localmode" ]; then
+  outputFlag="--output=type=docker"
 fi
 
 targetFlag=""
@@ -50,14 +62,16 @@ if [[ -n "$cacheref" ]] && [[ "$cachetype" = "local" ]]; then
     importCacheFlags="$importCacheFlags--cache-from=type=local,src=$ref "
   done
 fi
+if [ -n "$localmode" ]; then
+  importCacheFlags=""
+fi
 
 exportCacheFlags=""
 if [ "$PUSH" = "push" ]; then
   exportCacheFlags="--cache-to=type=inline "
 fi
 
-buildxCmd build $targetFlag $importCacheFlags $exportCacheFlags \
+buildxCmd build $targetFlag $importCacheFlags $exportCacheFlags $outputFlag \
   --platform "$PLATFORMS" \
   --tag "$REPO:$TAG$tagLatest" \
-  --output "type=image,$pushFlag" \
-  $currentref
+  $currentcontext
