chore: fix test dockerd bin perms
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
(cherry picked from commit fd3eeb1e13f4e6c3ec1de137e09f95008dc0503d)

diff --git a/hack/test b/hack/test
--- a/hack/test
+++ b/hack/test
@@ -13,9 +13,18 @@ set -eu -o pipefail
 : ${DOCKERFILE_RELEASES=}
 : ${BUILDKIT_WORKER_RANDOM=}
 
-if [ "$TEST_DOCKERD" == "1" ] && ! file $TEST_DOCKERD_BINARY | grep "statically linked" >/dev/null; then
-  echo "dockerd binary needs to be statically linked"
-  exit 1
+if [ "$TEST_DOCKERD" == "1" ]; then
+  if [ ! -f "$TEST_DOCKERD_BINARY" ]; then
+    echo "dockerd binary not found"
+    exit 1
+  fi
+  if [ ! -x "$TEST_DOCKERD_BINARY" ]; then
+    chmod +x "$TEST_DOCKERD_BINARY"
+  fi
+  if ! file "$TEST_DOCKERD_BINARY" | grep "statically linked" >/dev/null; then
+    echo "dockerd binary needs to be statically linked"
+    exit 1
+  fi
 fi
 
 if [ "$#" == 0 ]; then TEST_INTEGRATION=1; fi
