ci(buildkit): fix timeout for image job
Signed-off-by: CrazyMax <1951866+crazy-max@users.noreply.github.com>

diff --git a/.github/workflows/buildkit.yml b/.github/workflows/buildkit.yml
--- a/.github/workflows/buildkit.yml
+++ b/.github/workflows/buildkit.yml
@@ -27,7 +27,7 @@ env:
   IMAGE_NAME: "moby/buildkit"
   PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64,linux/s390x,linux/ppc64le,linux/riscv64"
   DESTDIR: "./bin"
-  BUILD_TIMEOUT: "900"  # 15 minutes
+  IMAGE_BUILD_TIMEOUT: "900"  # 15 minutes
 
 jobs:
   prepare:
@@ -177,12 +177,23 @@ jobs:
       -
         name: Build ${{ needs.prepare.outputs.tag }}
         run: |
-          timeout ${BUILD_TIMEOUT} ./hack/images "${{ needs.prepare.outputs.tag }}" "$IMAGE_NAME" "${{ needs.prepare.outputs.push }}"
-          if [ $? -eq 124 ]; then
-            echo "::error::Build timed out after ${BUILD_TIMEOUT} seconds"
-            docker kill --signal=SIGQUIT buildx_buildkit_${{ steps.buildx.outputs.name }}
-            exit 1
-          fi
+          ./hack/images "${{ needs.prepare.outputs.tag }}" "$IMAGE_NAME" "${{ needs.prepare.outputs.push }}" &
+          bpid=$!
+          sleepinter=10
+          iter=$(( ${{ env.IMAGE_BUILD_TIMEOUT }} / $sleepinter ))
+          for ((i = 0; i < iter; i++)); do
+            if ! kill -0 $bpid 2>/dev/null; then
+              exit 0
+            fi
+            sleep $sleepinter
+          done
+          echo "::error::Build timed out after ${IMAGE_BUILD_TIMEOUT} seconds"
+          set -x
+          docker exec buildx_buildkit_${{ steps.buildx.outputs.name }}0 ps aux
+          docker kill --signal=SIGQUIT buildx_buildkit_${{ steps.buildx.outputs.name }}0
+          kill -15 $bpid
+          wait $bpid
+          exit 1
         env:
           BUILDX_CMD: docker --debug buildx
           RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
